name: MultiTp
main: main.MtpMain
version: 1.15.2
api-version: 1.15
commands:
  mtp:
    description: Daje mozliwosc sprawdzenia,jakie statystyki prywatne posiada dany gracz.
    permission-message: You don't have admin.